modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory (36 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="resourceful_tools" #mandatory
version="1.2.10" #mandatory
displayName="Resourceful Tools" #mandatory
description='''
A set of simple tools that allow you to obtain difficult to get resources
'''


[[dependencies.resourceful_tools]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.resourceful_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.16.4, 1.16.5]"
    ordering="NONE"
    side="BOTH"
