modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory (24 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional

[[mods]] #mandatory
modId="resourceful_tools" #mandatory
version="1.1.25" #mandatory
displayName="Resourceful Tools" #mandatory
description='''
A set of simple tools that allow you to obtain difficult to get resources
'''


[[dependencies.resourceful_tools]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.resourceful_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
